// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoPVZbR6KQ3q1DcrLeiJn8574efHlCMu4',
    appId: '1:212902730047:web:30e627ca524d51a2455b8a',
    messagingSenderId: '212902730047',
    projectId: 'hasan-eke',
    authDomain: 'hasan-eke.firebaseapp.com',
    storageBucket: 'hasan-eke.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkknkzpvf3NWMYNwGXY_rXH70JTwb9vUQ',
    appId: '1:212902730047:android:516d873dbeffc68a455b8a',
    messagingSenderId: '212902730047',
    projectId: 'hasan-eke',
    storageBucket: 'hasan-eke.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyLLoNtYI9hKtuv7M2ihYvZk9oUt06IXU',
    appId: '1:212902730047:ios:3ac0342feef2e369455b8a',
    messagingSenderId: '212902730047',
    projectId: 'hasan-eke',
    storageBucket: 'hasan-eke.appspot.com',
    iosClientId:
        '212902730047-ob1ligohtjvsubr358c1pjmnee56u7dk.apps.googleusercontent.com',
    iosBundleId: 'com.hasaneke.hasaneke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyLLoNtYI9hKtuv7M2ihYvZk9oUt06IXU',
    appId: '1:212902730047:ios:3ac0342feef2e369455b8a',
    messagingSenderId: '212902730047',
    projectId: 'hasan-eke',
    storageBucket: 'hasan-eke.appspot.com',
    iosClientId:
        '212902730047-ob1ligohtjvsubr358c1pjmnee56u7dk.apps.googleusercontent.com',
    iosBundleId: 'com.hasaneke.hasaneke',
  );
}
